- name: Add bastion to dynamic host
  add_host:
    name: bastion
    group: bast
    ansible_ssh_user: cloud-user
    ansible_become: yes
- name: Add other hosts to nodes group
  add_host:
    name: "{{item.name}}"
    group: nodes
    ansible_ssh_user: cloud-user
    ansible_become: yes
  when: item.name != 'bastion'
  with_items: "{{guests}}"
- name: Add other hosts to ocs group
  add_host:
    name: "{{item.name}}"
    group: ocs
    ansible_ssh_user: cloud-user
    ansible_become: yes
  when: item.ocs_host is defined and item.ocs_host == 'true'
  with_items: "{{guests}}"
