---
- name: Create in-memory inventory
  gather_facts: no
  hosts: localhost
  vars_files:
  - vars/guests.yml
  roles:
  - inmemory_inventory

- name: Create hostpath volume for registry
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create raw image
    command: "qemu-img create -f raw /var/lib/libvirt/images/docker-registry.img {{registry_storage_size}}"
    args:
      creates: "/var/lib/libvirt/images/docker-registry.img"
    register: docker_registry_disk
  - name: Add new disk to infranode01 as {{registry_storage_device}}
    command: virsh attach-disk infranode01 --source /var/lib/libvirt/images/docker-registry.img --persistent --target {{registry_storage_device}}
    when: docker_registry_disk.changed
- name: Prepare infranode for hostpath
  hosts: infranode01
  tasks:
  - name: Makefs for docker registry
    filesystem:
      fstype: xfs
      dev: "/dev/{{registry_storage_device}}"
  - name: Mount new disk to mount point
    mount:
      path: /var/hostpath/registry
      src: "/dev/{{registry_storage_device}}"
      fstype: xfs
      state: mounted
  - name: Create mount point
    file:
      path: "/var/hostpath/registry"
      state: directory
      owner: nfsnobody
      group: nfsnobody
      mode: 0777
  - name: SELinux container_file_t
    command: "chcon -Rt container_file_t /var/hostpath/registry"
- name: Add hostpath volumen to registry
  hosts: master01
  tasks:
  - name: Add scc hostaccess
    command: "oc adm policy add-scc-to-user hostaccess -z registry"
  - name: Add volumen to regisry dc
    command: "oc volume dc/docker-registry --add -t hostPath --path /var/hostpath/registry -m /registry --name registry-storage --overwrite"
