---
- name: Create backup from iptables rules
  local_action:
    "shell iptables-save > /etc/sysconfig/iptables.org"

- name: Get master01 ip addr
  local_action:
    shell ip n | grep "`virsh dumpxml master01 | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`" | awk '{ gsub(/[\(\)]/,"",$1); print $1"" }'
  register: master_ip_addr

- name:
  debug:
    msg: |
      "master ip: {{master_ip_addr.stdout}}"

- name: Get infranode ip addr
  local_action:
    shell ip n | grep "`virsh dumpxml infranode01 | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`" | awk '{ gsub(/[\(\)]/,"",$1); print $1"" }'
  register: infranode_ip_addr

- name:
  debug:
    msg: |
      "master ip: {{infranode_ip_addr.stdout}}"
- name: create http nat for infra
  iptables:
    table: nat
    chain: PREROUTING
    destination: "{{hostvars['localhost']['ansible_default_ipv4']['address']}}"
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: DNAT
    to_destination: "{{infranode_ip_addr.stdout}}:80"
    comment: OCP - Redirect app http traffic to infranode

- name: create https nat for infra
  iptables:
    table: nat
    chain: PREROUTING
    destination: "{{hostvars['localhost']['ansible_default_ipv4']['address']}}"
    protocol: tcp
    match: tcp
    destination_port: 443
    jump: DNAT
    to_destination: "{{infranode_ip_addr.stdout}}:443"
    comment: OCP - Redirect app https traffic to infranode

- name: create https nat for master
  iptables:
    table: nat
    chain: PREROUTING
    destination: "{{hostvars['localhost']['ansible_default_ipv4']['address']}}"
    protocol: tcp
    match: tcp
    destination_port: 8443
    jump: DNAT
    to_destination: "{{master_ip_addr.stdout}}:8443"
    comment: OCP - Redirect console https traffic to master

- name: create https postrouting nat for master
  iptables:
    table: nat
    chain: POSTROUTING
    destination: "{{master_ip_addr.stdout}}"
    protocol: tcp
    match: tcp
    destination_port: 8443
    jump: MASQUERADE
    comment: OCP - Post routing rule from cluster to master

- name: create http postrouting nat for infra
  iptables:
    table: nat
    chain: POSTROUTING
    destination: "{{infranode_ip_addr.stdout}}"
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: MASQUERADE
    comment: OCP - Post routing rule from cluster to infra

- name: create https postrouting nat for infra
  iptables:
    table: nat
    chain: POSTROUTING
    destination: "{{infranode_ip_addr.stdout}}"
    protocol: tcp
    match: tcp
    destination_port: 443
    jump: MASQUERADE
    comment: OCP - Post routing rule from cluster to infra

- name: allow FORWARD for all guest network DNAT traffic
  iptables:
    chain: FORWARD
    match: state
    ctstate: NEW,RELATED,ESTABLISHED
    destination: 192.168.122.0/24
    jump: ACCEPT
    comment: OCP - Allow all DNAT FORWARD to guest network

- name: allow FORWARD for all guest network DNAT traffic
  iptables:
    chain: FORWARD
    match: state
    ctstate: NEW,RELATED,ESTABLISHED
    destination: 192.168.122.0/24
    jump: ACCEPT
    comment: OCP - Allow all DNAT FORWARD to guest network
- name: remove in virbr0 reject
  iptables:
    chain: FORWARD
    in_interface: virbr0
    jump: REJECT
    state: absent
- name: remove out virbr0 reject
  iptables:
    chain: FORWARD
    out_interface: virbr0
    jump: REJECT
    state: absent

- name: Persist iptables rules
  local_action:
    "shell iptables-save > /etc/sysconfig/iptables"
