- name: Install needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - container-selinux
    - atomic-openshift-docker-excluder

- name: Detect Docker storage configuration status
  command: grep -q /dev/mapper/docker /etc/sysconfig/docker-storage
  register: docker_storage_test
  changed_when: false
  failed_when: false

- name: Create Docker storage configuration
  copy:
    dest: /etc/sysconfig/docker-storage-setup
    content: |
      WIPE_SIGNATURES=true
      STORAGE_DRIVER=overlay2
      DEVS={{device}}
      CONTAINER_ROOT_LV_NAME=dockerlv
      CONTAINER_ROOT_LV_MOUNT_PATH=/var/lib/docker
      VG=ocp
  when: docker_storage_test.rc != 0
- name: Apply Docker storage configuration changes
  command: docker-storage-setup
  when: docker_storage_test.rc != 0

- name: Copy Docker registry certificate for OpenShift tools
  copy: src=cert.crt dest=/etc/pki/ca-trust/source/anchors/registry.crt follow=yes
  register: certificate_update
  when: openshift_docker_additional_registries is defined

- name: Update CA trust store
  command: /usr/bin/update-ca-trust
  when: certificate_update | changed

- name: Enable docker
  command: systemctl enable docker

- name: Start docker
  command: systemctl start docker
