- name: Install needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - container-selinux
    - atomic-openshift-docker-excluder

- name: Create Docker storage configuration
  copy:
    dest: /etc/sysconfig/docker-storage-setup
    content: |
      STORAGE_DRIVER=overlay2
      DEVS={{device}}
      CONTAINER_ROOT_LV_NAME=dockerlv
      CONTAINER_ROOT_LV_MOUNT_PATH=/var/lib/docker
      VG=ocp

- name: Copy Docker registry certificate for OpenShift tools
  copy: src=cert.crt dest=/etc/pki/ca-trust/source/anchors/registry.crt follow=yes
  register: certificate_update
  when: openshift_docker_additional_registries is defined

- name: Update CA trust store
  command: /usr/bin/update-ca-trust
  when: certificate_update | changed

- name: Enable docker
  command: systemctl enable docker

- name: Start docker
  command: systemctl start docker
