- name: Install needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - container-selinux
    - atomic-openshift-docker-excluder

- name: check are raw images created
  local_action: |
    shell ls /var/lib/libvirt/images/docker-{{ inventory_hostname}}.img
  register: ls_results
  changed_when: false
  failed_when: false

- name: create raw images for docker storage
  local_action: |
    shell qemu-img create -f raw /var/lib/libvirt/images/docker-{{ inventory_hostname}}.img {{docker_storage_size}}
  when: ls_results.rc > 0

- name: check is docker already attached
  local_action: |
    shell virsh dumpxml {{inventory_hostname}} | grep -q 'docker-{{inventory_hostname}}'
  register: disk_attached
  changed_when: false
  failed_when: false

- name: add new disk for docker as vdb
  local_action: |
    shell virsh attach-disk {{inventory_hostname}} --source /var/lib/libvirt/images/docker-{{inventory_hostname}}.img --persistent --target vdb
  when: disk_attached.rc > 0

- name: Detect Docker storage configuration status
  command: grep -q overlay2 /etc/sysconfig/docker-storage
  register: docker_storage_test
  changed_when: false
  failed_when: false


- name: Create Docker storage configuration
  copy:
    dest: /etc/sysconfig/docker-storage-setup
    content: |
      WIPE_SIGNATURES=true
      STORAGE_DRIVER=overlay2
      DEVS={{docker_storage_device}}
      CONTAINER_ROOT_LV_NAME=dockerlv
      CONTAINER_ROOT_LV_MOUNT_PATH=/var/lib/docker
      VG=ocp
  when: docker_storage_test.rc != 0
- name: wipefs to present random storage setup failure
  command: "wipefs -a -f {{docker_storage_device}}"
  when: docker_storage_test.rc != 0
- name: Apply Docker storage configuration changes
  command: docker-storage-setup
  when: docker_storage_test.rc != 0

- name: Copy Docker registry certificate for OpenShift tools
  copy: src=cert.crt dest=/etc/pki/ca-trust/source/anchors/registry.crt follow=yes
  register: certificate_update
  when: openshift_docker_additional_registries is defined

- name: Update CA trust store
  command: /usr/bin/update-ca-trust
  when: certificate_update | changed

- name: Enable docker
  command: systemctl enable docker

- name: Start docker
  command: systemctl start docker
