---
- name: Clean subscription from hosts
  hosts: all
  gather_facts: False
  tasks:
  - name: Unregister systems
    command: subscription-manager unregister
    ignore_errors: yes
    
- name: Clean up everything
  hosts: localhost
  gather_facts: False
  vars_files:
      - ../vars/guests.yml
  tasks:
  - name: Remove old known_hosts
    file:
      path: /root/.ssh/known_hosts
      state: absent
  - name: get list of vms
    virt: command=list_vms
    register: virt_vms
  - name: Detroy all VMs
    virt:
      command: destroy
      name: "{{item.name}}"
    when: item.name in virt_vms.list_vms
    with_items: "{{guests}}"
    ignore_errors: yes
  - name: Undefine all VMs
    virt:
      command: undefine
      name: "{{item.name}}"
    with_items: "{{guests}}"
    ignore_errors: yes
  - name: Remove temp files
    file:
      path: /tmp/inventory
      state: absent
  - name: Remove image file
    file:
      path: "/var/lib/libvirt/images/{{item.name}}*.qcow2"
      state: absent
    with_items: "{{guests}}"
