---
- name: Clean up everything
  hosts: localhost
  vars_files:
      - ../vars/guests.yml
  tasks:
  - name: Detroy all VMs
    virt:
      command: detroy
      name: "{{item.name}}"
    with_items: "{{guests}}"
  - name: Undefine all VMs
    virt:
      command: undefine
      name: "{{item.name}}"
  - name: Remove temp files
    file:
      path: /tmp/inventory
      state: absent
