---
- name: Create inventory for cleaning
  hosts: localhost
  gather_facts: False
  vars_files:
  - vars/guests.yml
  tasks:
  - name: Add host to inventory
    add_host:
      name: "{{item.name}}"
    with_items: "{{guests}}"
- name: Clean subscription from hosts
  hosts: all
  gather_facts: False
  tasks:
  - name: Unregister systems
    command: subscription-manager unregister
    ignore_errors: yes
- name: Clean up everything
  hosts: localhost
  gather_facts: False
  vars_files:
      - vars/guests.yml
  tasks:
  - name: Remove old known_hosts
    file:
      path: /root/.ssh/known_hosts
      state: absent
  - name: get list of vms
    virt: command=list_vms
    register: virt_vms
  - name: Detroy all VMs
    virt:
      command: destroy
      name: "{{item.name}}"
    when: item.name in virt_vms.list_vms
    with_items: "{{guests}}"
    ignore_errors: yes
  - name: Undefine all VMs
    virt:
      command: undefine
      name: "{{item.name}}"
    with_items: "{{guests}}"
    ignore_errors: yes
  - name: Remove temp files
    file:
      path: /tmp/inventory
      state: absent
  - name: Remove image files
    command: "rm -Rf /var/lib/libvirt/images/{{item.name}}*.qcow2"
    with_items: "{{guests}}"
  - name: Revert iptables changes
    copy:
      src: /etc/sysconfig/iptables.org
      dest: /etc/sysconfig/iptables
  - name: Restart iptables
    service:
      name: iptables
      state: restarted
