---
- name: Create inventory for cleaning
  hosts: localhost
  gather_facts: False
  vars_files:
  - vars/guests.yml
  roles:
  - inmemory_inventory
  
  tasks:
  - name: Remove old known_hosts
    file:
      path: /root/.ssh/known_hosts
      state: absent

  - name: stop virtual machines
    ignore_errors: yes
    virt:
      name: "{{ item.name }}"
      state: destroyed
    with_items: "{{ guests }}"

  - name: undefine virtual machines
    ignore_errors: yes
    virt:
      name: "{{ item.name }}"
      command: undefine
    with_items: "{{ guests }}"

  - name: delete cloud-init CDs for VMs
    file:
      path: "/var/lib/libvirt/images/cloud-init-{{ item.name }}.iso"
      state: absent
    with_items: "{{ guests }}"

  - name: delete dirs for userdata
    file:
      path: "/tmp/{{ item.name }}"
      state: absent
    with_items: "{{ guests }}"

  - name: delete logical volumes for virtual os disks
    lvol:
      vg: "{{ volume_group }}"
      lv: "{{ item.name}}-a"
      state: absent
      force: yes
    with_items: "{{ guests }}"

  - name: delete logical volumes for virtual docker disks
    lvol:
      vg: "{{ volume_group }}"
      lv: "{{ item.name }}-b"
      state: absent
      force: yes
    with_items: "{{ guests }}"
