---
- name: Setup virt env
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Install packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
    - qemu-kvm
    - libvirt
    - virt-install
    - bridge-utils
    - libselinux-python
    - iptables-services
    - guestfish
  - name: Update all packages
    yum:
      name: '*'
      state: latest
  - name: Enable libvirt
    service:
      name: libvirtd
      enabled: true
  - name: Start libvirtd
    service:
      name: libvirtd
      state: started
