---
- name: Prepare host and guests
  hosts: all
  tasks:
  - name: Add key to authorized_keys
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  - name: Run ssh-keyscan to add keys to known_hosts
    local_action: shell ssh-keyscan {{ inventory_hostname }} >> ~/.ssh/known_hosts
  - name: Copy etc hosts file to all hosts
    copy:
      src: /etc/hosts
      dest: /etc/hosts
