---
- name: Setup virt env
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Install packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
    - bridge-utils
    - qemu-kvm
    - qemu-img
    - libvirt
    - libvirt-python
    - libvirt-client
    - virt-install
    - libguestfs-tools
    - libguestfs-bash-completion
    - genisoimage
    - iptables-services
    - iptables
  - name: Update all packages
    yum:
      name: '*'
      state: latest
  - name: Enable libvirt
    service:
      name: libvirtd
      enabled: true
    register: libvirtd
  - name: Start libvirtd
    service:
      name: libvirtd
      state: started
  - name: Ensure iptables enabled and running
    service:
      name: iptables
      state: started
      enabled: yes
  - name: Destroy old pool, images
    command: virsh pool-destroy images
    when: libvirtd.changed
    ignore_errors: true
  - name: Undefine images pool
    command: virsh pool-undefine images
    when: libvirtd.changed
    ignore_errors: true
  - name: Create new default pool
    command: virsh pool-define-as --name default --type dir --target /var/lib/libvirt/images
    when: libvirtd.changed
  - name: Set autostart on pool default
    command: virsh pool-autostart default
    when: libvirtd.changed
  - name: Start default pool
    command: virsh pool-start default
    when: libvirtd.changed
