---
- name: Figure out pool id from bastion subscription
  hosts: bast
  gather_facts: False
  serial: 1
  tasks:
  - name: Register hosts
    command: subscription-manager register --force --username={{rhn_username}} --password={{rhn_password}}
    retries: 3
    delay: 1
  - name: Get pool id
    shell: "subscription-manager list --available --matches 'Employee SKU' --pool-only | tail -n 1"
    register: poolid
    retries: 3
    delay: 1
  - set_fact:
      poolid: "{{poolid.stdout}}"
  - set_fact:
      pwd: "{{rhn_password}}"
      user: "{{rhn_username}}"
- name: Register nodes to RHN and subscribe
  hosts: all
  gather_facts: False
  tasks:
  - name: Check Red Hat subscription
    redhat_subscription:
      state: present
      username: "{{ hostvars['bastion']['user'] }}"
      password: "{{ hostvars['bastion']['pwd'] }}"
      pool: "{{ hostvars['bastion']['poolid'] }}"
    register: subscribe
  - name: Disable all repos
    shell: |
      subscription-manager repos --disable=*
    when: subscribe.changed
  - name: Enable correct repos
    command: "subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-ose-3.6-rpms --enable=rhel-7-fast-datapath-rpms --enable=rhel-7-server-optional-rpms"
    when: subscribe.changed
  roles:
  - { role: yumstuff, packages: [wget,git,net-tools,bind-utils,iptables-services,bash-completion,nfs-utils,kexec-tools,sos,psacct]}

- name: Prepare bastion for OCP install
  gather_facts: False
  hosts: bast
  tasks:
  - name: Copy playbooks to bastion
    synchronize:
      src: /root/hetzner-ocp
      dest: /root/
  - name: Copy playbooks to bastion
    copy:
      src: "{{item}}"
      dest: "{{item}}"
      mode: 0600
    items:
    - '/root/.ssh/id_rsa'
    - '/root/.ssh/id_rsa.pub'
    - '/root/.ssh/known_hosts'
  - name: Create exports dir
    file:
      path: /exports
      state: directory
  - name: Makefs for exports
    command: mkfs.ext4 /dev/vdb
  - name: Mount new disk to mount point
    lineinfile:
      path: /etc/fstab
      state: present
      line: "/dev/vdb   /exports  ext4    defaults    0 0"
  - name: Refresh mounts
    command: mount -a
  roles:
  - { role: yumstuff, packages: [atomic-openshift-utils,atomic-openshift-clients]}

- name: Gather facts from localhost
  hosts: localhost
  tasks:
  - debug: msg='Gathering facts'
- name: Update 7.4 to latest
  hosts: nodes
  gather_facts: false
  tasks:
  - name: Update packages
    command: yum update -y
  - name: Shutdown
    shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible"
    async: 1
    poll: 0
    ignore_errors: true
  - name: Wait for host to come back up
    local_action:
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 5
      timeout: 300
- name: Create inventory
  hosts: bast
  vars:
    ip_addr: "{{hostvars['localhost']['ansible_default_ipv4']['address']}}"
  roles:
  - { role: inventory}
- name: Install docker
  gather_facts: False
  hosts: nodes
  roles:
  - { role: docker_setup, device: '/dev/vdb'}
