---
- name: Register bastion to RHN and subscribe
  hosts: bast
  gather_facts: False
  serial: 1
  tasks:
  - name: Register hosts
    command: subscription-manager register --force --username={{rhn_username}} --password={{rhn_password}}
    retries: 3
    delay: 1
    when: not do_not_subscribe
  - name: Get pool id
    shell: "subscription-manager list --available --matches 'Employee SKU' --pool-only | tail -n 1"
    register: poolid
    retries: 3
    delay: 1
    when: not do_not_subscribe
  - name: Subscribe hosts
    command: "subscription-manager attach --pool={{ poolid.stdout }}"
    retries: 3
    delay: 1
    when: not do_not_subscribe
  - set_fact:
      poolid: "{{poolid.stdout}}"
      pwd: "{{rhn_password}}"
      user: "{{rhn_username}}"
      do_not_subscribe: "{{do_not_subscribe}}"
- name: Register nodes to RHN and subscribe
  hosts: nodes
  gather_facts: False
  serial: 1
  tasks:
  - name: Register hosts
    command: subscription-manager register --force --username={{ hostvars['bastion']['user'] }} --password={{ hostvars['bastion']['pwd'] }}
    retries: 3
    delay: 1
    when: not hostvars['bastion']['do_not_subscribe']
  - name: Subscribe hosts
    command: "subscription-manager attach --pool={{ hostvars['bastion']['poolid'] }}"
    retries: 3
    delay: 1
    when: not hostvars['bastion']['do_not_subscribe']
- name: Manager repos
  hosts: all
  gather_facts: False
  vars:
    ose_ver: 3.6
  tasks:
  - name: Disable all repos
    command: subscription-manager repos --disable=*
  - name: Activate OCP repos
    command: "subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-ose-{{ose_ver}}-rpms --enable=rhel-7-fast-datapath-rpms --enable=rhel-7-server-optional-rpms"
- name: Prepare nodes for OCP install
  gather_facts: False
  hosts: nodes
  roles:
  - { role: yumstuff, packages: [wget,git,net-tools,bind-utils,iptables-services,bash-completion,nfs-utils,kexec-tools,sos,psacct]}
  - { role: docker_setup, device: '/dev/vdb'}
  - { role: prepare_node, disconnected: false, ntp_server: 0.rhel.pool.ntp.org, use_subs_mgr: true, ose_ver: 3.6}
- name: Prepare bastion for OCP install
  gather_facts: False
  hosts: bast
  tasks:
  - name: Copy playbooks to bastion
    synchronize:
      src: /root/hetzner-ocp
      dest: /root/
  roles:
  - { role: yumstuff, packages: [wget,git,net-tools,bind-utils,iptables-services,bash-completion,nfs-utils,kexec-tools,sos,psacct,atomic-openshift-utils]}
