---
- name: Prepare bastion for OCP install
  hosts: bastion
  gather_facts: False
  serial: 1
  vars:
    ose_ver: 3.6
  vars_prompt:
    - name: "rhn_username"
      prompt: "Enter RHN username"
      private: no
    - name: "rhn_password"
      prompt: "Enter RHN password"
      private: yes
  tasks:
  - name: Figure out pool id
    shell: subscription-manager list --available --matches 'Employee SKU' | grep Pool | awk '{print $3}'
    register: poolid
  - name: Register hosts
    command: subscription-manager register --username={{rhn_username}} --password={{rhn_password}}
  - name: Attach to Openshift subscription
    command: "subscription-manager attach --pool={{poolid.stdout}}"
  - name: Disable all repos
    command: subscription-manager repos --disable=*
  - name: Activate OCP repos
    command: "subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-ose-{{ose_ver}}-rpms --enable=rhel-7-fast-datapath-rpms --enable=rhel-7-server-optional-rpms"
  - name: Install packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - nfs-utils
    - kexec-tools
    - sos
    - psacct
    - atomic-openshift-utils
  - name: yum update
    yum:
      name: '*'
      state: latest
  - name: Copy playbooks to bastion
    synchronize:
      src: /root/hetzner-ocp
      dest: /root/
