---
- name: Register hosts to RHN
  hosts: all
  serial: 1
  vars_prompt:
  - name: "rhn_username"
    prompt: "Enter RHN username"
    private: no
  - name: "rhn_password"
    prompt: "Enter RHN password"
    private: yes
  tasks:
  - name: Register hosts
    command: subscription-manager register --username={{rhn_username}} --password={{rhn_password}}
- name: Prepare bastion for OCP install
  hosts: all
  vars:
    ose_ver: 3.6
  roles:
  - { role: subscribe, ose_ver: "{{ose_ver}}"}
  - { role: yumstuff, packages: [wget,git,net-tools,bind-utils,iptables-services,bash-completion,nfs-utils,kexec-tools,sos,psacct]}
