- name: Provision quests
  hosts: localhost
  vars_files:
      - ../vars/guests.yml
  tasks:
      - name: start libvirtd
        service: name=libvirtd state=started enabled=yes
        register: libvirtd

      - name: wait for libvirtd to get up
        pause: seconds=10
        when: libvirtd.changed

      - name: get list of vms
        virt: command=list_vms
        register: virt_vms

      - name: create vm
        command: "virt-install --name {{item.name}}
                 --connect qemu:///system
                 --arch x86_64
                 --ram {{ item.mem }}
                 --vcpus {{ item.cpu }}
                 --cpu host
                 --location {{ item.url }}
                 --os-type {{ item.os.type }}
                 --os-variant {{ item.os.variant }}
                 --network {{item.network}}
                 --graphics vnc
                 --{{item.virt_hypervisor}}
                 --virt-type {{ item.virt_type }}
                 --disk size={{item.disks.os.size}},{{item.disks.os.options}}
                 --disk size={{item.disks.data.size}},{{item.disks.data.options}}
                 --extra-args '{{item.extra_args}}'
                 --noautoconsole
                 --noreboot"
        when: item.name not in virt_vms.list_vms
        with_items: "{{guests}}"
      - name: Wait 20 secs for all VMs to get IP
        pause:
          seconds: 20
      - name: Clean up etc hosts
        lineinfile:
          path: /etc/hosts
          state: absent
          regexp: "{{item.name}}"
        with_items: "{{guests}}"
      - name: Initialize etc hosts
        lineinfile:
          path: /etc/hosts
          state: present
          line: "{{item}}"
        with_items:
        - 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
        - ::1 localhost localhost.localdomain localhost6 localhost6.localdomain6
      - name: Rewrite etc hosts
        local_action:
          shell ip n | grep "`virsh dumpxml {{item.name}} | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`" | awk '{ gsub(/[\(\)]/,"",$1); print $1" {{item.name}}" }' >> /etc/hosts
        with_items: "{{guests}}"
      - name: Remove old inventory
        file:
          path: /tmp/inventory
          state: absent
      - name: Create simple ansible inventory
        local_action:
          shell echo {{item.name}} >> /tmp/inventory
        with_items: "{{guests}}"
