- name: Provision quests
  hosts: localhost
  gather_facts: true
  vars_files:
      - ../vars/guests.yml
  tasks:
      - name: start libvirtd
        service: name=libvirtd state=started enabled=yes
        register: libvirtd

      - name: wait for libvirtd to get up
        pause: seconds=10
        when: libvirtd.changed

      - name: get list of vms
        virt: command=list_vms
        register: virt_vms

      - name: create vm
        command: "virt-install --name {{item.name}}
                 --connect qemu:///system
                 --arch x86_64
                 --ram {{ item.mem }}
                 --vcpus {{ item.cpu }}
                 --cpu host
                 --location {{ item.url }}
                 --os-type {{ item.os.type }}
                 --os-variant {{ item.os.variant }}
                 --network {{item.network}}
                 --graphics vnc
                 --{{item.virt_hypervisor}}
                 --virt-type {{ item.virt_type }}
                 --disk size={{item.disks.os.size}},{{item.disks.os.options}}
                 --disk size={{item.disks.data.size}},{{item.disks.data.options}}
                 --extra-args '{{item.extra_args}}'
                 --noautoconsole
                 --autostart"
        when: item.name not in virt_vms.list_vms
        with_items: "{{guests}}"
      - name: Wait 20 secs for all VMs to get IP
        pause:
          seconds: 20
      - name: Clean up etc hosts
        lineinfile:
          path: /etc/hosts
          state: absent
          regexp: "{{item.name}}"
        with_items: "{{guests}}"
      - name: Initialize etc hosts
        lineinfile:
          path: /etc/hosts
          state: present
          line: "{{item}}"
        with_items:
        - 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
        - ::1 localhost localhost.localdomain localhost6 localhost6.localdomain6
      - name: Rewrite etc hosts
        local_action:
          shell ip n | grep "`virsh dumpxml {{item.name}} | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`" | awk '{ gsub(/[\(\)]/,"",$1); print $1" {{item.name}}" }' >> /etc/hosts
        with_items: "{{guests}}"
      - name: Remove old inventory
        file:
          path: /root/inventory
          state: absent
      - name: Create groups to inventory
        local_action:
          shell echo '[bast]' >> /root/inventory && echo 'bastion' >> /root/inventory && echo '[nodes]' >> /root/inventory
      - name: Create simple ansible inventory
        local_action:
          shell echo {{item.name}} >> /root/inventory
        with_items: "{{guests}}"
        when: item.name != 'bastion'
      - name: Get master01 ip addr
        local_action:
          shell ip n | grep "`virsh dumpxml master01 | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`" | awk '{ gsub(/[\(\)]/,"",$1); print $1"" }'
        register: master_ip_addr
      - name: Get infranode ip addr
        local_action:
          shell ip n | grep "`virsh dumpxml infranode01 | grep "mac address" | sed "s/.*'\(.*\)'.*/\1/g"`" | awk '{ gsub(/[\(\)]/,"",$1); print $1"" }'
        register: infranode_ip_addr
      - name: Port forwarding for 80
        local_action:
          "shell iptables -t nat -I PREROUTING -p tcp -d {{hostvars['localhost']['ansible_default_ipv4']['address']}} --dport 80 -j DNAT --to-destination {{infranode_ip_addr.stdout}}:80"
      - name: Port forwarding for 443
        local_action:
          "shell iptables -t nat -I PREROUTING -p tcp -d {{hostvars['localhost']['ansible_default_ipv4']['address']}} --dport 443 -j DNAT --to-destination {{infranode_ip_addr.stdout}}:443"
      - name: Port forwarding for 8443
        local_action:
          "shell iptables -t nat -I PREROUTING -p tcp -d {{hostvars['localhost']['ansible_default_ipv4']['address']}} --dport 8443 -j DNAT --to-destination {{master_ip_addr.stdout}}:8443"
      - name: Change forward rule for guest subnet
        local_action:
          "shell iptables -I FORWARD -m state -d 192.168.122.0/24 --state NEW,RELATED,ESTABLISHED -j ACCEPT"
      - name: Port 80 postroute masq
        local_action:
          "shell iptables -t nat -I POSTROUTING -d {{infranode_ip_addr.stdout}} --dport 80 -j MASQUERADE
      - name: Port 443 postroute masq
        local_action:
          "shell iptables -t nat -I POSTROUTING -d {{infranode_ip_addr.stdout}} --dport 443 -j MASQUERADE
      - name: Port 8443 postroute masq
        local_action:
          "shell iptables -t nat -I POSTROUTING -d {{master_ip_addr.stdout}} --dport 8443 -j MASQUERADE
      - name: Perist iptables rules
        local_action:
          "shell iptables-save > /etc/sysconfig/iptables"
