---
- name: Collect RHN account information and create SSH key
  hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: rhn_username
    prompt: RHN username
    private: no
  - name: rhn_password
    prompt: RHN password
    private: yes
  tasks:
  - set_fact:
      pwd: "{{rhn_password}}"
      user: "{{rhn_username}}"
  - name: Create SSH key for root
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /root/.ssh/id_rsa

- name: Create in-memory inventory
  gather_facts: no
  hosts: localhost
  vars_files:
  - vars/guests.yml
  roles:
  - inmemory_inventory

- name: Setup and prepare nodes.
  hosts: all
  gather_facts: no
  vars_files:
  - vars/guests.yml
- include: prepare_libvirt.yml
- include: provision.yml
- include: prepare_ssl.yml
- include: prepare_guests.yml
