---
- name: Setup virt env
  hosts: localhost
  tasks:
  - name: Install packages
    dnf:
      name: {{item}}
      state: present
    with_items:
    - '@Virtualization'
    - libselinux-python
  - name: Enable libvirt
    service:
      name: libvirtd
      enabled: true
  - name: Start libvirtd
    service:
      name: libvirtd
      state: started
  - name: Create SSH key for root
  - user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
