---
- name: Collect RHN account information
  hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: rhn_username
    prompt: RHN username
    private: no
  - name: rhn_password
    prompt: RHN password
    private: yes
  tasks:
  - set_fact:
      pwd: "{{rhn_password}}"
      user: "{{rhn_username}}"
      
- name: Setup and prepare nodes.
  hosts: all
  gather_facts: no
  vars_files:
  - vars/guests.yml
  tasks:
  - name: Add bastion to dynamic host
    add_host:
      name: bastion
      group: bast
  - name: Add other hosts to nodes group
    add_host:
      name: "{{item.name}}"
      group: nodes
    when: item.name != 'bastion'
    with_items: "{{guests}}"
- include: prepare_libvirt.yml
- include: provision.yml
- include: prepare_ssl.yml
- include: prepare_guests.yml
