---
- name: Collect RHN account information and create SSH key
  hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: rhsm_username
    prompt: RHSM username
    private: no
  - name: rhsm_password
    prompt: RHSM password
    private: yes
  - name: rhsm_poolid
    prompt: Subscription Pool ID
    private: no
  - name: registry_username
    prompt: RH registry username (RHN pwd or token https://docs.openshift.com/container-platform/3.11/install_config/configuring_red_hat_registry.html)
    private: no
  - name: registry_password
    prompt: RH registry password
    private: yes
  tasks:
  - set_fact:
      pwd: "{{rhsm_password}}"
      user: "{{rhsm_username}}"
      oreg_auth_user: "{{registry_password}}"
      oreg_auth_password: "{{registry_username}}"
  - set_fact:
      poolid: "{{rhsm_poolid}}"
    when: rhsm_poolid is defined
  - name: Create SSH key for root
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /root/.ssh/id_rsa

- name: Create in-memory inventory
  gather_facts: no
  hosts: localhost
  vars_files:
  - vars/guests.yml
  roles:
  - inmemory_inventory

- name: Setup and prepare nodes.
  hosts: all
  gather_facts: no
  vars_files:
  - vars/guests.yml
- import_playbook: prepare_host.yml
- import_playbook: provision.yml
- import_playbook: prepare_ssl.yml
- import_playbook: prepare_guests.yml
