---
- name: Start all VMs
  hosts: localhost
  gather_facts: False
  vars_files:
      - ../vars/guests.yml
  tasks:
  - name: Start all VMs
    virt:
      command: start
      name: "{{item.name}}"
    with_items: "{{guests}}"
    ignore_errors: yes
