---
- name: Install virtualization
  hosts: localhost
  tasks:
  - name: Install packages
    dnf:
      name: '@Virtualization'
      state: present
  - name: Enable libvirt
    service:
      name: libvirtd
      enabled: true
  - name: Start libvirtd
    service:
      name: libvirtd
      state: started
