- name: Create new user
  hosts: master01
  gather_facts: false
  vars_prompt:
  - name: username
    prompt: Username
    private: false
  - name: password
    prompt: Password
    private: true
  tasks:
  - name: Add user
    command: "htpasswd -b /etc/origin/master/htpasswd {{username}} {{password}}"
