- name: check are raw images created
  local_action: |
    shell ls /var/lib/libvirt/images/cns-{{ inventory_hostname}}.img
  register: ls_results
  changed_when: false
  failed_when: false

- name: create raw images for cns
  local_action: |
    shell qemu-img create -f raw /var/lib/libvirt/images/cns-{{ inventory_hostname}}.img {{cns_storage_size}}
  when: ls_results.rc > 0

- name: check is cns storage already attached
  local_action: |
    shell virsh dumpxml {{inventory_hostname}} | grep -q 'cns-{{inventory_hostname}}'
  register: disk_attached
  changed_when: false
  failed_when: false

- name: add new disk for cns disk as {{cns_storage_device}}
  local_action: |
    shell virsh attach-disk {{inventory_hostname}} --source /var/lib/libvirt/images/cns-{{inventory_hostname}}.img --persistent --target {{cns_storage_device}}
  when: disk_attached.rc > 0

